### ISSUE TITLE
Need Information about building this code on my machine

### ISSUE THREAD

**Issue by Boruto0752** [openshift/driver-toolkit#133]
I want to build this code I tried to run this Dockerfile on my CENTOS machine but first got an error about pulling the image so I replaced the base image with quay.io/openshift-release-dev/ocp-release:4.12.21-x86_64 and wanted to build it got a subscription manager not found as error and then tried it on the AWS OCP cluster on which replace the buildconfig Dockerfile with this Dockerfile got Updating Subscription Management repositories Unable to read consumer identity Subscription Manager is operating in container mode as error so I want to build this image from scratch instead of ready image

**Comment by ybettan** [comment]
Hello @Boruto0752.

I am afraid this is not possible without a RHEL subscription.
This is why we have prebuilt DTK (driver-toolkit) images for each Openshift z-stream released.

Your options are:
* Build this image locally on a subscribed RHEL machine
* Pull the prebuilt image for your cluster version using.
```
oc adm release info quay.io/openshift-release-dev/ocp-release:<requested cluster version>-x86_64 --image-for=driver-toolkit # x86
oc adm release info quay.io/openshift-release-dev/ocp-release:<requested cluster version>-aarch64 --image-for=driver-toolkit # ARM
```

Hope this help.

**Comment by ybettan** [comment]
/close
Closing as there are no action items on it.
